name: Mise à jour Agenda

on:
  schedule:
    - cron: '45 1 * * *'  # tous les jours à 7h00 UTC
  workflow_dispatch: # pour lancement manuel

jobs:
  update_calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          pip install requests google-api-python-client google-auth-httplib2 google-auth-oauthlib icalendar

      - name: Définir les variables d'environnement
        run: |
          echo "ICS_URL=${{ secrets.ICS_URL }}" >> $GITHUB_ENV
          echo "CALENDAR_ID=${{ secrets.CALENDAR_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }}" >> $GITHUB_ENV
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> $GITHUB_ENV
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> $GITHUB_ENV
          echo "NOTIFY_EMAIL=${{ secrets.NOTIFY_EMAIL }}" >> $GITHUB_ENV

      - name: Lancer le script
        run: python ton_script.py
