name: Synchronisation EDT quotidienne

on:
  schedule:
    # Exécution tous les jours à 02h UTC (03h en heure française en hiver, 04h en été)
    - cron: '0 2 * * *'
  workflow_dispatch:  # Permet de déclencher manuellement le workflow depuis l'interface GitHub

jobs:
  sync-calendar:
    name: Synchroniser l'EDT avec Google Calendar
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Exécuter le script de synchronisation
        env:
          ICS_URL: ${{ secrets.ICS_URL }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python sync_ics_to_google_calendar.py
